repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.5
    hooks:
      - id: isort
        language_version: python3.9
  - repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins,
          flake8-comprehensions,
          flake8-print,
          flake8-eradicate,
        ]
        language_version: python3.9
        args: [
          --max-line-length=127,
          '--ignore=D105,D200,W503,F401,F811'
        ]
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        language: system
        types: [python]
        args: [
          --max-public-methods=32,
          --max-args=8,
          '--disable=logging-fstring-interpolation,logging-not-lazy,unspecified-encoding,too-few-public-methods,too-many-instance-attributes',
          '--good-names=ip,rc,eval,vm,ls',
          '--load-plugins=pylint_pytest'
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        verbose: true
        entry: bash -c 'mypy "$@" || true' --
        additional_dependencies: [types-PyYAML, types-paramiko]
